require "rubygems"
require "bundler"
require "dotenv"
require "webrick"

require "coffee_script"
require "therubyracer"
require "image_optim"
require "zlib"
require "zip"

require "maglove/version"
require "maglove/helper/log_helper"
# require "maglove/command/theme"
# require "maglove/command/core"
# require "maglove/command/compile"
# require "maglove/command/compress"
# require "maglove/command/copy"
# require "maglove/command/util"
# require "maglove/command/font"
# require "maglove/command/sync"
# require "maglove/command/server"
require "maglove/phantom_script"
require "maglove/asset/theme"
# require "maglove/server/hpub"
# require "maglove/server"
require "maglove/template/tumblr"
